### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by tanteng** [forecho/awesome-yii2#4]
你好，看了你的博客，希望能够跟你建立友链，同是技术博客，关注WEB开发，不知可否？
http://www.tantengvip.com

**Comment by forecho** [comment]
我也看了你博客，有些文章确实还不错，希望坚持。友链的话，我暂时可以用 http://www.getyii.com 跟你交换吧，我的博客暂时还没有友链这个模块，你看如何？

**Comment by tanteng** [comment]
如此甚好，我已做好贵站的链接！可能有缓存等待更新！
