### ISSUE TITLE
套用其他模板

### ISSUE THREAD

**Issue by zhaochunyang** [forecho/awesome-yii2#9]
有没有好看的后台模板推荐  顺带套用方式 谢谢

**Comment by qiansen1386** [comment]
@zhaochunyang http://themeforest.net/tags/backend 好看的就在这里。都挺便宜的，商业项目的话随便买一个好了。不可能超支的。

免费的后端模板，记得目前为止只有一个[adminLTE](https://almsaeedstudio.com/preview)比较好看

**Comment by prodcd** [comment]
有个AceAdmin不错，不过套用起来麻烦点。

**Comment by forecho** [comment]
https://github.com/iiYii/yii2-adminlte adminLTE 可以参考这个
